const GET_MODELS = 'GET_MODELS';
const MODELS_RETURNED = 'MODELS_RETURNED';
const CREATE_APP = 'CREATE_APP';
const APP_CREATED = 'APP_CREATED';
const ERROR = 'ERROR';

module.exports = {
  GET_MODELS,
  MODELS_RETURNED,
  CREATE_APP,
  APP_CREATED,
  ERROR
};